[profile.release]
opt-level = "z"
debug = false
lto = true
# codegen-units = 1
panic = "unwind"
strip = true
incremental = true

# [target.aarch64-apple-darwin]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/ld64.mold"]
